### PR TITLE
Season 4 update

### PR DESCRIPTION
**Pull request by justindriggers**
Updating for a friend, thought this could save you some time. I'm not exactly sure what to do with the raid info, since the ilvls per boss "index" are different between the raids.

### CODE REVIEW

**Comment by filliph** [comment]
Re. Boss indexes, I'm not sure what to do about that either. It's incredibly inconvenient to have three different breakdowns.

I think in my WIP copy I just said heck it and went with the Amirdrassil breakdown.

**Comment by justindriggers** [comment]
I'm actually not particularly familiar with the addon so I'll just ask you directly: where can I see the results of that mixin in the UI? I can play around with a few things.

**Comment by filliph** [comment]
I'll do a more thorough review around May 8th when I'm back, but at first glance it looks good 👍 

Do you have a reliable way of fetching the bonusIDs or did you gather the data manually / via Wowhead? In the six months or so between seasons I keep forgetting how to find them on Wago.tools 🤔

**Comment by justindriggers** [comment]
I usually just search through https://www.raidbots.com/static/data/live/bonuses.json or https://github.com/simulationcraft/simc/blob/dragonflight/SpellDataDump/bonus_ids.txt - when in doubt, I add the bonusID to the Wowhead URL and see what it spits out. I agree it's a bit annoying 😂

**Comment by filliph** [comment]
> I'm actually not particularly familiar with the addon so I'll just ask you directly: where can I see the results of that mixin in the UI? I can play around with a few things.

I believe it's via `/iut` then the "Raid" tab 🤔

**Comment by filliph** [comment]
> I usually just search through https://www.raidbots.com/static/data/live/bonuses.json or https://github.com/simulationcraft/simc/blob/dragonflight/SpellDataDump/bonus_ids.txt - when in doubt, I add the bonusID to the Wowhead URL and see what it spits out. I agree it's a bit annoying 😂 

Ahhh those will help a lot going forward, thanks!

**Pull request merged**
